name: Dummy CI

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main

pr:
  paths:
    include:
      - main

stages:
  - stage: Hello World
    jobs:
      - job: Foo
        steps:
          - script: echo Hello World!