name: Dummy CI

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .devops/ci.yml
      - src/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - .devops/ci.yml
      - src/*

stages:
  - stage: Hello_World
    jobs:
      - job: Foo
        steps:
          - script: echo Hello World2!
          - task: PowerShell@2
            inputs:
              pwsh: true
              script: |
                throw "somthing bad happenend"
              failOnStderr: true
              targetType: inline
