name: Dummy CI

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - db

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - db

stages:
  - stage: Hello_World
    jobs:
      - job: Foo
        steps:
          - script: echo Hello World!