name: Dummy CI

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .devops/ci.yml
      - src/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - .devops/ci.yml
      - src/*

stages:
  - stage: Hello_World
    jobs:
      - job: Foo
        steps:
          - script: echo Hello World!