name: Dummy DB

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .devops/db.yml
    - db/*

pr: none

stages:
  - stage: Hello_World
    jobs:
    - job: Foo
      steps:
      - script: echo Hello World!